var powerArray = ["B0R_X_MR4","B0R_X_MR3","B0R_X_MR2","B0R_X_MR1","B0R_X_PR4","B0R_X_PR3","B0R_X_PR2","B0R_X_PR1","B0R_X_VR4","B0R_X_VR3","B0R_X_VR2","B0R_X_VR1","B0R_X_ER4","B0R_X_ER3","B0R_X_ER2","B0R_X_ER1"];
var powerArray2 = ["B0R_X_MR4","B0R_X_MR3","B0R_X_MR2","B0R_X_MR1","B0R_X_MR0","B0R_X_PR4","B0R_X_PR3","B0R_X_PR2","B0R_X_PR1","B0R_X_PR0","B0R_X_VR4","B0R_X_VR3","B0R_X_VR2","B0R_X_VR1","B0R_X_VR0","B0R_X_ER4","B0R_X_ER3","B0R_X_ER2","B0R_X_ER1","B0R_X_ER0"];
var mainPowerArray = ["B0R_X_MR4","B0R_X_MR3","B0R_X_MR2","B0R_X_MR1","B0R_X_MR0","B0R_X_VR4","B0R_X_VR3","B0R_X_VR2","B0R_X_VR1","B0R_X_VR0"];
var instantSpecialCards = ["B0B_R_SG","B0B_G_EO","B0S_Y_BO","B0S_Y_MP","B0S_B_SP"]
var resolutionSpecialCards = ["B0B_R_SG","B0B_G_EO",]

var cardList = {
    cards: {
        basic_locations: [{
            "cardTitle": "Fighter Launch Bay",
            "cardImage": "fighter_launch_bay.png",
            "cardColour": "R",
            "type": "basic",
            "cardDeck": "Base",
            "cardQuantity": {
                "p3": 3,
                "p4": 4
            },
            "cardEndGame": false,
			"cardResolution":0,
            "im_score": 7,
            "cardCreditCost": 4,
            "cardPowerCost": 1,
            "cardMaxAdditionalPoints": Infinity,
            "cardMaxPlayable": Infinity,
            "cardFunction": false,
			"cardLocationRestriction": [["B0R_X_MR4",3],["B0R_X_MR3",3],["B0R_X_MR2",3],["B0R_X_MR1",3],["B0R_X_MR0",3],["B0R_X_VR4",3],["B0R_X_VR3",3],["B0R_X_VR2",3],["B0R_X_VR1",3],["B0R_X_VR0",3]],
            "cardDescription": "Cannot be placed with <span class='distanceModifier'> 3  </span> of the <i>Main Reactor</i>",
            "cardId": "B0B_R_FLB"
        }, {
            "cardTitle": "Shield Generator",
            "cardImage": "shield_generator.png",
            "cardColour": "R",
            "type": "basic",
            "cardDeck": "Base",
            "cardQuantity": {
                "p3": 3,
                "p4": 4
            },
            "cardEndGame": false,
			"cardResolution":1,
            "im_score": 4,
            "cardCreditCost": 3,
            "cardPowerCost": 1,
            "cardMaxAdditionalPoints": 4,
            "cardMaxPlayable": 1,
            "cardFunction": true,
            "cardLocationRestriction": [],
            "cardDescription": "<span class='pointModifier'>+2</span> for each additional power spent when playing <i>Shield Generator</i>",
            "cardId": "B0B_R_SG"
        }, {
            "cardTitle": "Turret",
            "cardImage": "turret.png",
            "cardColour": "R",
            "type": "basic",
            "cardDeck": "Base",
            "cardQuantity": {
                "p3": 3,
                "p4": 4
            },
            "cardEndGame": true,
			"cardResolution":0,
            "im_score": 2,
            "cardCreditCost": 1,
            "cardPowerCost": 1,
            "cardMaxAdditionalPoints": Infinity,
            "cardMaxPlayable": Infinity,
            "cardFunction": true,
            "cardLocationRestriction": [],
            "cardDescription": "<span class='pointModifier'>+1</span> for each other <i>Turret</i> on the Station",
            "cardId": "B0B_R_T"
        }, {
            "cardTitle": "Alien Bazaar",
            "cardImage": "alien_bazaar.png",
            "cardColour": "Y",
            "type": "basic",
            "cardDeck": "Base",
            "cardQuantity": {
                "p3": 3,
                "p4": 4
            },
            "cardEndGame": true,
			"cardResolution":0,			
            "im_score": 3,
            "cardCreditCost": 3,
            "cardPowerCost": 0,
            "cardMaxAdditionalPoints": Infinity,
            "cardMaxPlayable": Infinity,
            "cardFunction": true,
            "cardLocationRestriction": [],
            "cardDescription": "<span class='pointModifier'>+2</span> if there are 3 more Green locations within <span class='distanceModifier'> 2  </span>",
            "cardId": "B0B_Y_AB"
        }, {
            "cardTitle": "Customs",
            "cardImage": "customs.png",
            "cardColour": "Y",
            "type": "basic",
            "cardDeck": "Base",
            "cardQuantity": {
                "p3": 3,
                "p4": 4
            },
            "cardEndGame": false,
			"cardResolution":0,			
            "im_score": 3,
            "cardCreditCost": 2,
            "cardPowerCost": 0,
            "cardMaxAdditionalPoints": Infinity,
            "cardMaxPlayable": Infinity,
            "cardFunction": true,
            "cardLocationRestriction": [],
            "cardDescription": "<span class='creditModifier'>+1</span> for each adjacent Yellow location",
            "cardId": "B0B_Y_C"
        }, {
            "cardTitle": "Energy Market",
            "cardImage": "energy_market.png",
            "cardColour": "Y",
            "type": "basic",
            "cardDeck": "Base",
            "cardQuantity": {
                "p3": 3,
                "p4": 4
            },
            "cardEndGame": false,
			"cardResolution":0,			
            "im_score": 2,
            "cardCreditCost": 3,
            "cardPowerCost": 0,
            "cardMaxAdditionalPoints": Infinity,
            "cardMaxPlayable": Infinity,
            "cardFunction": true,
            "cardLocationRestriction": [],
            "cardDescription": "<span class='creditModifier'>+1</span> for each <i>Power Reactor</i> in the Station (Max <span class='creditModifier'>+3</span>)",
            "cardId": "B0B_Y_EM"
        }, {
            "cardTitle": "Garden",
            "cardImage": "garden.png",
            "cardColour": "P",
            "type": "basic",
            "cardDeck": "Base",
            "cardQuantity": {
                "p3": 3,
                "p4": 4
            },
            "cardEndGame": false,
			"cardResolution":0,			
            "im_score": 3,
            "cardCreditCost": 3,
            "cardPowerCost": 0,
            "cardMaxAdditionalPoints": Infinity,
            "cardMaxPlayable": Infinity,
            "cardFunction": true,
            "cardLocationRestriction": [],
            "cardDescription": "<span class='pointModifier'>+1</span> if there is no Red location within <span class='distanceModifier'> 3  </span>  <br><span class='pointModifier'>+1</span> if there is no <i>Power Station</i> within <span class='distanceModifier'> 2  </span>",
            "cardId": "B0B_P_G"
        }, {
            "cardTitle": "Holographic Display Area",
            "cardImage": "holographic_display_area.png",
            "cardColour": "P",
            "type": "basic",
            "cardDeck": "Base",
            "cardQuantity": {
                "p3": 3,
                "p4": 4
            },
            "cardEndGame": false,
			"cardResolution":0,			
            "im_score": 2,
            "cardCreditCost": 2,
            "cardPowerCost": 1,
            "cardMaxAdditionalPoints": Infinity,
            "cardMaxPlayable": Infinity,
            "cardFunction": true,
            "cardLocationRestriction": [],
            "cardDescription": "<span class='pointModifier'>+1</span> for every adjacent location",
            "cardId": "B0B_P_HDA"
        }, {
            "cardTitle": "Restaurant",
            "cardImage": "restaurant.png",
            "cardColour": "P",
            "type": "basic",
            "cardDeck": "Base",
            "cardQuantity": {
                "p3": 3,
                "p4": 4
            },
            "cardEndGame": false,
			"cardResolution":0,			
            "im_score": 0,
            "cardCreditCost": 3,
            "cardPowerCost": 0,
            "cardMaxAdditionalPoints": Infinity,
            "cardMaxPlayable": Infinity,
            "cardFunction": true,
            "cardLocationRestriction": [],
            "cardDescription": "<span class='pointModifier'>+1</span> for every location type in the Station",
            "cardId": "B0B_P_R"
        }, {
            "cardTitle": "Ambassador Quarters",
            "cardImage": "ambassador_quarters.png",
            "cardColour": "G",
            "type": "basic",
            "cardDeck": "Base",
            "cardQuantity": {
                "p3": 3,
                "p4": 4
            },
            "cardEndGame": false,
			"cardResolution":0,			
            "im_score": 2,
            "cardCreditCost": 2,
            "cardPowerCost": 0,
            "cardMaxAdditionalPoints": Infinity,
            "cardMaxPlayable": Infinity,
            "cardFunction": true,
            "cardLocationRestriction": [],
            "cardDescription": "<span class='pointModifier'>+1</span> if placed adjacent to a Green location<br><span class='midSpacer'>OR</span><br><span class='pointModifier'>+2</span> if placed adjacent to <i>Embassy Offices</i>",
            "cardId": "B0B_G_AQ"
        }, {
            "cardTitle": "Council Room",
            "cardImage": "council_room.png",
            "cardColour": "G",
            "type": "basic",
            "cardDeck": "Base",
            "cardQuantity": {
                "p3": 3,
                "p4": 4
            },
            "cardEndGame": true,
			"cardResolution":0,			
            "im_score": 3,
            "cardCreditCost": 3,
            "cardPowerCost": 0,
            "cardMaxAdditionalPoints": Infinity,
            "cardMaxPlayable": 1,
            "cardFunction": true,
            "cardLocationRestriction": [],
            "cardDescription": "<span class='pointModifier'>+1</span> for each other station that does not contain a <i>Council Room</i>",
            "cardId": "B0B_G_CR"
        }, {
            "cardTitle": "Embassy Offices",
            "cardImage": "embassy_offices.png",
            "cardColour": "G",
            "type": "basic",
            "cardDeck": "Base",
            "cardQuantity": {
                "p3": 3,
                "p4": 4
            },
            "cardEndGame": false,
			"cardResolution":1,			
            "im_score": 2,
            "cardCreditCost": 2,
            "cardPowerCost": 0,
            "cardMaxAdditionalPoints": Infinity,
            "cardMaxPlayable": Infinity,
            "cardFunction": true,
            "cardLocationRestriction": [],
            "cardDescription": "You may choose another player when you build this location. They gain <span class='pointModifier'>+1</span> and you gain <span class='pointModifier'>+2</span>",
            "cardId": "B0B_G_EO"
        }, {
            "cardTitle": "Command Centre",
            "cardImage": "command_centre.png",
            "cardColour": "B",
            "type": "basic",
            "cardDeck": "Base",
            "cardQuantity": {
                "p3": 3,
                "p4": 4
            },
            "cardEndGame": true,
			"cardResolution":0,			
            "im_score": 0,
            "cardCreditCost": 5,
            "cardPowerCost": 1,
            "cardMaxAdditionalPoints": 8,
            "cardMaxPlayable": 1,
            "cardFunction": true,
            "cardLocationRestriction": [],
            "cardDescription": "<span class='pointModifier'>+1</span> for each Blue location on the Station",
            "cardId": "B0B_B_CC"
        }, {
            "cardTitle": "Crew Quarters",
            "cardImage": "crew_quarters.png",
            "cardColour": "B",
            "type": "basic",
            "cardDeck": "Base",
            "cardQuantity": {
                "p3": 3,
                "p4": 4
            },
            "cardEndGame": false,
			"cardResolution":0,			
            "im_score": 1,
            "cardCreditCost": 1,
            "cardPowerCost": 0,
            "cardMaxAdditionalPoints": Infinity,
            "cardMaxPlayable": Infinity,
            "cardFunction": true,
            "cardLocationRestriction": [],
            "cardDescription": "<span class='pointModifier'>+2</span> if placed adjacent to another <i>Crew Quarters</i>",
            "cardId": "B0B_B_CQ"
        }, {
            "cardTitle": "Docking Bay",
            "cardImage": "docking_bay.png",
            "cardColour": "B",
            "type": "basic",
            "cardDeck": "Base",
            "cardQuantity": {
                "p3": 3,
                "p4": 4
            },
            "cardEndGame": false,
			"cardResolution":0,			
            "im_score": 1,
            "cardCreditCost": 3,
            "cardPowerCost": 0,
            "cardMaxAdditionalPoints": 4,
            "cardMaxPlayable": Infinity,
            "cardFunction": true,
            "cardLocationRestriction": [],
            "cardDescription": "<span class='pointModifier'>+1</span> for each location between <i>Docking Bay</i> and <i>Main Reactor</i>",
            "cardId": "B0B_B_DB"
        }, {
            "cardTitle": "Medical Facility",
            "cardImage": "medical_facility.png",
            "cardColour": "B",
            "type": "basic",
            "cardDeck": "Base",
            "cardQuantity": {
                "p3": 3,
                "p4": 4
            },
            "cardEndGame": false,
			"cardResolution":0,			
            "im_score": 3,
            "cardCreditCost": 3,
            "cardPowerCost": 1,
            "cardMaxAdditionalPoints": 4,
            "cardMaxPlayable": Infinity,
            "cardFunction": true,
            "cardLocationRestriction": [],
            "cardDescription": "<span class='pointModifier'>+1</span> for each <i>Power Reactor</i> within <span class='distanceModifier'> 3  </span> of <i>Medical Facility</i>",
            "cardId": "B0B_B_MF"
        }, {
            "cardTitle": "Security Station",
            "cardImage": "security_station.png",
            "cardColour": "B",
            "type": "basic",
            "cardDeck": "Base",
            "cardQuantity": {
                "p3": 3,
                "p4": 4
            },
            "cardEndGame": true,
			"cardResolution":0,			
            "im_score": 2,
            "cardCreditCost": 2,
            "cardPowerCost": 0,
            "cardMaxAdditionalPoints": Infinity,
            "cardMaxPlayable": Infinity,
            "cardFunction": true,
            "cardLocationRestriction": [],
            "cardDescription": "<span class='pointModifier'>+1</span> if <i>Security Station</i> has 4 adjacent locations",
            "cardId": "B0B_B_SS"
        }, {
            "cardTitle": "Transportation Platform",
            "cardImage": "transportation_platform.png",
            "cardColour": "B",
            "type": "basic",
            "cardDeck": "Base",
            "cardQuantity": {
                "p3": 3,
                "p4": 4
            },
            "cardEndGame": false,
			"cardResolution":0,			
            "im_score": 1,
            "cardCreditCost": 1,
            "cardPowerCost": 0,
            "cardMaxAdditionalPoints": Infinity,
            "cardMaxPlayable": Infinity,
            "cardFunction": true,
            "cardLocationRestriction": [],
            "cardDescription": "<span class='pointModifier'>+1</span> for each <i>Transportation Plaform</i> in the Station",
            "cardId": "B0B_B_TP"
        }],
        s_locations: [{
            "cardTitle": "Alliance Fleet Base",
            "cardImage": "alliance_fleet_base.png",
            "cardColour": "R",
            "type": "S",
            "cardDeck": "Base",
            "cardQuantity": 2,
            "cardEndGame": true,
			"cardResolution":0,			
            "im_score": 4,
            "cardCreditCost": 3,
            "cardPowerCost": 1,
            "cardMaxAdditionalPoints": Infinity,
            "cardMaxPlayable": Infinity,
            "cardFunction": true,
            "cardLocationRestriction": [],
            "cardDescription": "<span class='pointModifier'>+2</span> if you have more Red locations than Green locations",
            "cardId": "B0S_R_AFB"
        }, {
            "cardTitle": "Heavy Ion Cannon",
            "cardImage": "Heavy_ion_cannon.png",
            "cardColour": "R",
            "type": "S",
            "cardDeck": "Base",
            "cardQuantity": 2,
            "cardEndGame": false,
			"cardResolution":0,			
            "im_score": 6,
            "cardCreditCost": 3,
            "cardPowerCost": 2,
            "cardMaxAdditionalPoints": Infinity,
            "cardMaxPlayable": Infinity,
            "cardFunction": true,
            "cardLocationRestriction": [],
            "cardDescription": "<span class='pointModifier'>+2</span> if you have 3 or more <i>Power Reactors</i> in the Station",
            "cardId": "B0S_R_HIC"
        }, {
            "cardTitle": "Pilot Training Area",
            "cardImage": "pilot_training_area.png",
            "cardColour": "R",
            "type": "S",
            "cardDeck": "Base",
            "cardQuantity": 2,
            "cardEndGame": false,
			"cardResolution":0,			
            "im_score": 2,
            "cardCreditCost": 2,
            "cardPowerCost": 0,
            "cardMaxAdditionalPoints": Infinity,
            "cardMaxPlayable": Infinity,
            "cardFunction": true,
            "cardLocationRestriction": [],
            "cardDescription": "<span class='pointModifier'>+1</span>if placed adjacent to a Red location<br><span class='midSpacer'>OR</span><br><span class='pointModifier'>+2</span>if placed adjacent to <i>Fighter Launch Bay</i>",
            "cardId": "B0S_R_PTA"
        }, {
            "cardTitle": "Turret",
            "cardImage": "turret.png",
            "cardColour": "R",
            "type": "S",
            "cardDeck": "Base",
            "cardQuantity": 1,
            "cardEndGame": true,
			"cardResolution":0,			
            "im_score": 2,
            "cardCreditCost": 1,
            "cardPowerCost": 1,
            "cardMaxAdditionalPoints": Infinity,
            "cardMaxPlayable": Infinity,
            "cardFunction": true,
            "cardLocationRestriction": [],
            "cardDescription": "<span class='pointModifier'>+1</span> for each other <i>Turret</i> on the Station",
            "cardId": "B0S_R_T"
        }, {
            "cardTitle": "War Room",
            "cardImage": "war_room.png",
            "cardColour": "R",
            "type": "S",
            "cardDeck": "Base",
            "cardQuantity": 2,
            "cardEndGame": true,
			"cardResolution":0,			
            "im_score": 0,
            "cardCreditCost": 3,
            "cardPowerCost": 0,
            "cardMaxAdditionalPoints": 5,
            "cardMaxPlayable": Infinity,
            "cardFunction": true,
            "cardLocationRestriction": [],
            "cardDescription": "<span class='pointModifier'>+1</span> for each Red location on the Station",
            "cardId": "B0S_R_WR"
        }, {
            "cardTitle": "Business Offices",
            "cardImage": "business_offices.png",
            "cardColour": "Y",
            "type": "S",
            "cardDeck": "Base",
            "cardQuantity": 2,
            "cardEndGame": false,
			"cardResolution":1,			
            "im_score": 1,
            "cardCreditCost": 1,
            "cardPowerCost": 0,
            "cardMaxAdditionalPoints": Infinity,
            "cardMaxPlayable": Infinity,
            "cardFunction": true,
            "cardLocationRestriction": [],
            "cardDescription": "Pay up to <span class='creditModifier2'>6</span> and put them on this card. At the end of the year, you get them back. <span class='pointModifier'>+1</span> for every <span class='creditModifier2'>2</span> you put on the card",
            "cardId": "B0S_Y_BO"
        }, {
            "cardTitle": "Galactic Bank",
            "cardImage": "galactic_bank.png",
            "cardColour": "Y",
            "type": "S",
            "cardDeck": "Base",
            "cardQuantity": 2,
            "cardEndGame": false,
			"cardResolution":0,			
            "im_score": 4,
            "cardCreditCost": 3,
            "cardPowerCost": 1,
            "cardMaxAdditionalPoints": Infinity,
            "cardMaxPlayable": Infinity,
            "cardFunction": true,
            "cardLocationRestriction": [],
            "cardDescription": "At the beginning of every remaining year, you receive <span class='creditModifier'>+1</span>",
            "cardId": "B0S_Y_GB"
        }, {
            "cardTitle": "Trade Union Headquarters",
            "cardImage": "trade_union_headquarters.png",
            "cardColour": "Y",
            "type": "S",
            "cardDeck": "Base",
            "cardQuantity": 2,
            "cardEndGame": false,
			"cardResolution":0,			
            "im_score": 1,
            "cardCreditCost": 4,
            "cardPowerCost": 0,
            "cardMaxAdditionalPoints": 5,
            "cardMaxPlayable": Infinity,
            "cardFunction": true,
            "cardLocationRestriction": [],
            "cardDescription": "<span class='pointModifier'>+1</span> for each Yellow location on the Station",
            "cardId": "B0S_Y_TUH"
        }, {
            "cardTitle": "Galactic Resort",
            "cardImage": "galactic_resort.png",
            "cardColour": "P",
            "type": "S",
            "cardDeck": "Base",
            "cardQuantity": 2,
            "cardEndGame": true,
			"cardResolution":0,			
            "im_score": 0,
            "cardCreditCost": 3,
            "cardPowerCost": 0,
            "cardMaxAdditionalPoints": 5,
            "cardMaxPlayable": Infinity,
            "cardFunction": true,
            "cardLocationRestriction": [],
            "cardDescription": "<span class='pointModifier'>+1</span> for each Purple location in the Station",
            "cardId": "B0S_P_GR"
        }, {
            "cardTitle": "Observation Dome",
            "cardImage": "observation_dome.png",
            "cardColour": "P",
            "type": "S",
            "cardDeck": "Base",
            "cardQuantity": 2,
            "cardEndGame": false,
			"cardResolution":0,			
            "im_score": 3,
            "cardCreditCost": 2,
            "cardPowerCost": 0,
            "cardMaxAdditionalPoints": Infinity,
            "cardMaxPlayable": Infinity,
            "cardFunction": true,
            "cardLocationRestriction": [],
            "cardDescription": "You may not place other locations adjacent to <i>Observation Dome</i>",
            "cardId": "B0S_P_OD"
        }, {
            "cardTitle": "Opera House",
            "cardImage": "opera_house.png",
            "cardColour": "P",
            "type": "S",
            "cardDeck": "Base",
            "cardQuantity": 2,
            "cardEndGame": true,
			"cardResolution":0,			
            "im_score": 1,
            "cardCreditCost": 2,
            "cardPowerCost": 0,
            "cardMaxAdditionalPoints": Infinity,
            "cardMaxPlayable": Infinity,
            "cardFunction": true,
            "cardLocationRestriction": [],
            "cardDescription": "<span class='pointModifier'>+1</span> for each different adjacent location type",
            "cardId": "B0S_P_OH"
        }, {
            "cardTitle": "Sports Arena",
            "cardImage": "sports_arena.png",
            "cardColour": "P",
            "type": "S",
            "cardDeck": "Base",
            "cardQuantity": 2,
            "cardEndGame": false,
			"cardResolution":0,			
            "im_score": 3,
            "cardCreditCost": 3,
            "cardPowerCost": 0,
            "cardMaxAdditionalPoints": Infinity,
            "cardMaxPlayable": Infinity,
            "cardFunction": true,
            "cardLocationRestriction": [],
            "cardDescription": "<span class='pointModifier'>+1</span> for every year remaining",
            "cardId": "B0S_P_SA"
        }, {
            "cardTitle": "Alien Temple",
            "cardImage": "alien_temple.png",
            "cardColour": "G",
            "type": "S",
            "cardDeck": "Base",
            "cardQuantity": 2,
            "cardEndGame": true,
			"cardResolution":0,			
            "im_score": 0,
            "cardCreditCost": 3,
            "cardPowerCost": 0,
            "cardMaxAdditionalPoints": 5,
            "cardMaxPlayable": Infinity,
            "cardFunction": true,
            "cardLocationRestriction": [],
            "cardDescription": "<span class='pointModifier'>+1</span> for each Green location in the Station",
            "cardId": "B0S_G_AT"
        }, {
            "cardTitle": "Alliance Headquarters",
            "cardImage": "alliance_headquarters.png",
            "cardColour": "G",
            "type": "S",
            "cardDeck": "Base",
            "cardQuantity": 2,
            "cardEndGame": true,
			"cardResolution":0,			
            "im_score": 4,
            "cardCreditCost": 4,
            "cardPowerCost": 0,
            "cardMaxAdditionalPoints": Infinity,
            "cardMaxPlayable": 1,
            "cardFunction": true,
            "cardLocationRestriction": [],
            "cardDescription": "<span class='pointModifier'>+1</span> for each other Station with more Red locations than yours",
            "cardId": "B0S_G_AH"
        }, {
            "cardTitle": "Backup Reactor",
            "cardImage": "backup_reactor.png",
            "cardColour": "B",
            "type": "S",
            "cardDeck": "Base",
            "cardQuantity": 2,
            "cardEndGame": false,
			"cardResolution":0,			
            "im_score": 2,
            "cardCreditCost": 2,
            "cardPowerCost": 0,
            "cardMaxAdditionalPoints": Infinity,
            "cardMaxPlayable": Infinity,
            "cardFunction": true,
            "cardLocationRestriction": [],
            "cardDescription": "Add one energy to <i>Main Reactor</i><br><span class='pointModifier'>+1</span> if placed adjacent to <i>Main Reactor</i>",
            "cardId": "B0S_B_BR"
        }, {
            "cardTitle": "Cargo Hold",
            "cardImage": "cargo_hold.png",
            "cardColour": "B",
            "type": "S",
            "cardDeck": "Base",
            "cardQuantity": 2,
            "cardEndGame": false,
			"cardResolution":0,			
            "im_score": 2,
            "cardCreditCost": 2,
            "cardPowerCost": 0,
            "cardMaxAdditionalPoints": Infinity,
            "cardMaxPlayable": Infinity,
            "cardFunction": true,
            "cardLocationRestriction": [],
            "cardDescription": "<span class='pointModifier'>+1</span> if placed next to Blue location<br><span class='midSpacer'>OR</span><br><span class='pointModifier'>+2</span> if placed next to <i>Docking Bay</i>",
            "cardId": "B0S_B_CH"
        }, {
            "cardTitle": "Communications Beacon",
            "cardImage": "communications_beacon.png",
            "cardColour": "B",
            "type": "S",
            "cardDeck": "Base",
            "cardQuantity": 2,
            "cardEndGame": true,
			"cardResolution":0,			
            "im_score": 2,
            "cardCreditCost": 2,
            "cardPowerCost": 0,
            "cardMaxAdditionalPoints": Infinity,
            "cardMaxPlayable": Infinity,
            "cardFunction": true,
            "cardLocationRestriction": [],
            "cardDescription": "<span class='pointModifier'>+2</span> if <i>Communications Beacon</i> is the location furthest from the <i>Main Reactor</i>",
            "cardId": "B0S_B_CB"
        }, {
            "cardTitle": "Life Support Systems",
            "cardImage": "life_support.png",
            "cardColour": "B",
            "type": "S",
            "cardDeck": "Base",
            "cardQuantity": 2,
            "cardEndGame": true,
			"cardResolution":0,			
            "im_score": 0,
            "cardCreditCost": 4,
            "cardPowerCost": 1,
            "cardMaxAdditionalPoints": Infinity,
            "cardMaxPlayable": Infinity,
            "cardFunction": true,
            "cardLocationRestriction": [],
            "cardDescription": "<span class='pointModifier'>+1</span> for every 3 locations in the Station",
            "cardId": "B0S_B_LSS"
        }, {
            "cardTitle": "Solar Panels",
            "cardImage": "solar_panels.png",
            "cardColour": "B",
            "type": "S",
            "cardDeck": "Base",
            "cardQuantity": 2,
            "cardEndGame": false,
			"cardResolution":1,			
            "im_score": 2,
            "cardCreditCost": 1,
            "cardPowerCost": 0,
            "cardMaxAdditionalPoints": Infinity,
            "cardMaxPlayable": Infinity,
            "cardFunction": true,
            "cardLocationRestriction": [["B0R_X_MR4",1],["B0R_X_MR3",1],["B0R_X_MR2",1],["B0R_X_MR1",1],["B0R_X_MR0",1],["B0R_X_PR4",1],["B0R_X_PR3",1],["B0R_X_PR2",1],["B0R_X_PR1",1],["B0R_X_PR0",1],["B0R_X_PR4",1],["B0R_X_PR3",1],["B0R_X_PR2",1],["B0R_X_PR1",1],["B0R_X_PR0",1],["B0R_X_ER4",1],["B0R_X_ER3",1],["B0R_X_ER2",1],["B0R_X_ER1",1],["B0R_X_ER0",1]],
            "cardDescription": "May only be built adjacent to a <i>Power Reactor</i>. Add a power cube to that Reactor",
            "cardId": "B0S_B_SP"
        }, {
            "cardTitle": "Transportation Platform",
            "cardImage": "transportation_platform.png",
            "cardColour": "B",
            "type": "S",
            "cardDeck": "Base",
            "cardQuantity": 1,
            "cardEndGame": false,
			"cardResolution":0,			
            "im_score": 1,
            "cardCreditCost": 1,
            "cardPowerCost": 0,
            "cardMaxAdditionalPoints": Infinity,
            "cardMaxPlayable": Infinity,
            "cardFunction": true,
            "cardLocationRestriction": [],
            "cardDescription": "<span class='pointModifier'>+1</span> for each <i>Transportation Plaform</i> in the Station",
            "cardId": "B0S_B_TP"
        }],
		reactors: [{
		    "cardTitle": "Power Reactor",
            "cardImage": "power_generator.png",
            "type": "R",
            "cardDeck": "Base",
            "cardQuantity": 20,
            "cardEndGame": false,
			"cardResolution":0,			
            "im_score": 0,
            "cardCreditCost": 1,
            "cardPowerCost": 0,
            "cardMaxAdditionalPoints": Infinity,
            "cardMaxPlayable": Infinity,
            "cardFunction": false,
            "cardLocationRestriction": [],
            "cardDescription": "Provides two Power<br>",
            "cardId": "B0R_X_PR"
		},{
		    "cardTitle": "Main Reactor",
            "cardImage": "main_reactor.png",
            "type": "R",
            "cardDeck": "Base",
            "cardQuantity": 20,
            "cardEndGame": false,
			"cardResolution":0,			
            "im_score": 0,
            "cardCreditCost": 0,
            "cardPowerCost": 0,
            "cardMaxAdditionalPoints": Infinity,
            "cardMaxPlayable": Infinity,
            "cardFunction": false,
            "cardLocationRestriction": [],
            "cardDescription": "Provides two Power<br>Counts as <i>Power Reactor</i>",
            "cardId": "B0R_X_MR"
		},{
		    "cardTitle": "Vak Main Reactor",
            "cardImage": "main_reactor.png",
            "type": "R",
            "cardDeck": "Base",
            "cardQuantity": 20,
            "cardEndGame": false,
			"cardResolution":0,			
            "im_score": 0,
            "cardCreditCost": 0,
            "cardPowerCost": 0,
            "cardMaxAdditionalPoints": Infinity,
            "cardMaxPlayable": Infinity,
            "cardFunction": false,
            "cardLocationRestriction": [],
            "cardDescription": "Provides two Power<br>Counts as <i>Power Reactor</i><br>Counts as a location of every colour type",
            "cardId": "B0R_X_VR"
		}],
        conflict_cards : [{
			cardTitle: "Dispute (Green)",
			cardDescription: "Choose another player and count the number of green location in each of your Space Stations. If you have more, gain VP equal to the difference. They lose the same amount",
			cardCreditCost: 1,
			cardDeck: "Base",
			type : "Conflict",
			conflictType: "Dispute",
			cardMax: "3",
			cardId: "B0C_D_001"
		},{
			cardTitle: "Dispute (Red)",
			cardDescription: "Choose another player and count the number of red location in each of your Space Stations. If you have more, gain VP equal to the difference. They lose the same amount",
			cardCreditCost: 1,
			type : "Conflict",			
			cardDeck: "Base",
			conflictType: "Dispute",
			cardMax: "3",
			cardId: "B0C_D_002"
		},{
			cardTitle: "Dispute (Yellow)",
			cardDescription: "Choose another player and count the number of yellow location in each of your Space Stations. If you have more, gain VP equal to the difference. They lose the same amount",
			cardCreditCost: 1,
			type : "Conflict",			
			cardDeck: "Base",
			conflictType: "Dispute",
			cardMax: "3",
			cardId: "B0C_D_003"
		},{
			cardTitle: "Dispute (Blue)",
			cardDescription: "Choose another player and count the number of blue location in each of your Space Stations. If you have more, gain VP equal to the difference. They lose the same amount",
			cardCreditCost: 1,
			cardDeck: "Base",
			type : "Conflict",			
			conflictType: "Dispute",
			cardMax: "3",
			cardId: "B0C_D_004"
		},{
			cardTitle: "Dispute (Purple)",
			cardDescription: "Choose another player and count the number of purple location in each of your Space Stations. If you have more, gain VP equal to the difference. They lose the same amount",
			cardCreditCost: 1,
			cardDeck: "Base",
			type : "Conflict",			
			conflictType: "Dispute",
			cardMax: "3",
			cardId: "B0C_D_005"
		},{
			cardTitle: "Dispute (Reactors)",
			cardDescription: "Choose another player and count the number of Power Reactors in each of your Space Stations. If you have more, gain VP equal to the difference. They lose the same amount",
			cardCreditCost: 1,
			cardDeck: "Base",
			type : "Conflict",			
			conflictType: "Dispute",
			cardMax: "3",
			cardId: "B0C_D_006"
		}],
		banned :[{
            "cardTitle": "Galactic Research Council",
            "cardImage": "galactic_research_facility.png",
            "cardColour": "G",
            "type": "S",
            "cardDeck": "Base",
            "cardQuantity": 2,
            "cardEndGame": false,
			"cardResolution":2,			
            "im_score": 3,
            "cardCreditCost": 3,
            "cardPowerCost": 1,
            "cardMaxAdditionalPoints": Infinity,
            "cardMaxPlayable": Infinity,
            "cardFunction": true,
            "cardLocationRestriction": [],
            "cardDescription": "Each <b>other</b> player secretly chooses up to <span class='creditModifier2'>3</span> to pay and gains that amount in <span class='pointModifier2'>  </span><br>You gain <span class='pointModifier2'>  </span> equal to the highest amount paid, plus one",
            "cardId": "B0S_G_GRC"
        },{
            "cardTitle": "School of Alien Culture",
            "cardImage": "school_of_alien_cultures.png",
            "cardColour": "G",
            "type": "S",
            "cardDeck": "Base",
            "cardQuantity": 2,
            "cardEndGame": false,
			"cardResolution":2,			
            "im_score": 2,
            "cardCreditCost": 3,
            "cardPowerCost": 0,
            "cardMaxAdditionalPoints": Infinity,
            "cardMaxPlayable": Infinity,
            "cardFunction": true,
            "cardLocationRestriction": [],
            "cardDescription": "Each other player secretly chooses to either pay <span class='creditModifier2'>1</span> or lose <span class='pointModifier'> 2 </span>.  You get <span class='pointModifier'>+2</span> for each <span class='creditModifier2'>1</span> paid",
            "cardId": "B0S_G_SoAC"
        }, {
            "cardTitle": "Market Place",
            "cardImage": "market_place.png",
            "cardColour": "Y",
            "type": "S",
            "cardDeck": "Base",
            "cardQuantity": 2,
            "cardEndGame": false,
			"cardResolution":2,			
            "im_score": 2,
            "cardCreditCost": 3,
            "cardPowerCost": 0,
            "cardMaxAdditionalPoints": Infinity,
            "cardMaxPlayable": Infinity,
            "cardFunction": true,
            "cardLocationRestriction": [],
            "cardDescription": "Choose up to 2 other players. Get a combination of <span class='creditModifier2'>2</span> from them",
            "cardId": "B0S_Y_MP"
        }]
    }
}
